### ISSUE TITLE
Snippets MetaData Load Job - File Schema from snippets admin has changed

### ISSUE THREAD

**Issue by gkabbz** [mozilla/marketing-analytics#10]
Starting Aug 21st 2019 the file schema for the csv received from snippets admin tool with the metadata information changed. Changes included:
1. Addition of an additional column
2. Rearrangement of the file with the snippet ID going to the end of the file 
3. A smaller file 
As a result of the changes the job to load the metadata information into bigquery failed as the schema for the table doesn't match the schema in the file. 

Upon discussion with @glogiotatidis via slack, a new field was added called the job_id which appears first in the file and the snippet_id that used to appear first is now in the last column. 

A couple of issues that need to be investigated / fixed:
1. As the snippet_id was the field we used to join across the different data sources i.e. telemetry, metadata and GA, we need to confirm whether it's still showing up in GA. @glogiotatidis confirmed that in telemetry it has been replaced with the job_id.
2. Determine why the data drop has reduced in size
3. Determine if / how the join between the datasets should be fixed

**Comment by glogiotatidis** [comment]
See also https://github.com/mozmeao/snippets-service/issues/1121

**Comment by glogiotatidis** [comment]
We can go and revert telemetry to use `snippet_id` and also move `snippet_id` column at the start of the CSV metadata file, to make things work like they used to, while we figure out a solution for this one.

This can be done quickly if you want @gkabbz

**Comment by glogiotatidis** [comment]
Also a question going fwd is where we want to use `job id` or `snippet id` in the `utm_term` of any links used in snippets. Now we're using `snippet id` and I think we probably want to change this to `job id`. 

See also https://github.com/mozmeao/snippets-service/issues/1121

**Comment by jgmize** [comment]
This issue is no longer relevant. The current plan is to import the snippets metadata into the same BigQuery instance the snippets user events telemetry data is moving to.
